### PR TITLE
Features/movie list genres

### PR DESCRIPTION
**Pull request by bedicooper**
I've updated movie list saga to fetch a list of genres from API and save it to store (maybe we can use it?) _(1)_
as well as a formatting function for movie list data - in the same manner as previously with movie details.
I used the genres List to assign names to IDs in movie list objects.

If You will accept my change of heart for Main component in [PR #20](https://github.com/bedicooper/movies-browser/pull/20) I will update this PR and add `<Main>` to the index, so please review #20 first :)

_(1) i thought that maybe it is enough to ask API for genresList just once and then use the stored array for instance in People Details, but I'm not sure. What if someone enters our app not on the homepage (movie list) but on any different page, for example via URL that person got from someone else? Then the movie list saga never runs and we never ask API for genresList.
Maybe we need to have a separate saga that handles that single fetch once when App first renders? Or just ask for it every time_ 😛

### CODE REVIEW

**Comment by bedicooper** [comment]
Since I was editing the movie list I also used the Rating component to show votes on movie tiles.

**Review by patrycja-gomza — CHANGES_REQUESTED** [review]
Great job on the pull request! I really appreciate the effort you put into updating the movie list saga and incorporating a formatting function for the movie list data 👏

I also like the idea of having a separate saga for the genresList, especially to ensure it gets fetched when the application first renders. Your consideration about users entering the app through different pages raises a valid point. Having a dedicated saga for the initial fetch when the app renders for the first time seems like a good solution 🙌

I fully support the idea of creating a separate saga for genresList, and I think it will enhance the overall efficiency of our application. Please go ahead and make the necessary updates. I'll be happy to review and accept the pull request.

Thanks for your hard work and thoughtful considerations! 🎉

**Comment by bedicooper** [comment]
I've added the wrapping Main to the Page, as well as updated the useEffect on manual URL change - to disable two types of a request: 
1. page number over 500
2. a query with decimal fraction - it would display number with a fraction in pagination component.

**Review by patrycja-gomza — APPROVED** [review]
Great improvements! I appreciate your responsiveness. Your addition of Main to the Page and the updates to the useEffect show a thoughtful consideration of potential issues.

👍 Approved! Your changes look solid, and I'm confident they will enhance the functionality and maintainability of our codebase. Thanks for your dedication and for being receptive to feedback. Keep up the excellent work! 🚀

**Comment by bedicooper** [comment]
Thanks, I will resolve minor conflicts and after merge deploy the app to pages

**Pull request merged**
