### PR TITLE
Features/movie list

### PR DESCRIPTION
**Pull request by patrycja-gomza**
Hi!😊 This is just one initial part of MovieList. I mainly cared about json data handling and Redux implementation. The component has not been styled in any way yet, because I focused on functionality, so that you can use this part while I'm away (I'm going on vacation today and will be back on 03.01.24). Bye 👋
- - - 🌟 Merry Christmas!!! 🎄🎅🌟

### CODE REVIEW

**Comment by bedicooper** [comment]
Hi, I've assigned myself to Your branch and PR. I will push some commits here while You are gone, so we can deploy our app with a landing page ;) plus a want to implement routing with links to movieDetails page.

**Comment by bedicooper** [comment]
@widmo200 I urgently need your review to merge this PR

**Review by patrycja-gomza — COMMENTED** [review]
Great job @bedicooper! Thank you for expanding the code 😃 I approve all your changes.

**Review by widmo200 — APPROVED** [review]
good job ;)

**Pull request merged**
