### PR TITLE
update readme - final version

### PR DESCRIPTION
**Pull request by patrycja-gomza**
## Update README - Final Version

Description:
- Updated the Overview section to provide a more comprehensive introduction.
- Moved points from the "What We Are Working On" section to the "Features" section, removing the entire "What We Are Working On" section.
- Updated the GIF preview of our application to improve quality.
- Added a new GIF to showcase the functionality of the search feature.

Please review. Thank you! 🙏

### CODE REVIEW

**Review by bedicooper — COMMENTED** [review]
Great additions, Thanku You! 🙏 
could You update lines 144-154 as well to better reflect our new file structure? 👍

**Comment by patrycja-gomza** [comment]
> Great additions, Thanku You! 🙏 could You update lines 144-154 as well to better reflect our new file structure? 👍

I completely forgot about that. I've already made the change, and I apologize for any oversight. Please review 🙏

**Review by bedicooper — APPROVED** [review]
Superb!
All in all, You've done a wonderfull job with our README! Thank You very very much, it looks stunning!
🚀 🔥

**Review by widmo200 — APPROVED** [review]
very good !

**Comment by patrycja-gomza** [comment]
> Superb!
> All in all, You've done a wonderfull job with our README! Thank You very very much, it looks stunning!
> 🚀 🔥 

Thank you 😊

**Comment by patrycja-gomza** [comment]
> very good !

Thank you 😊

**Pull request merged**
