### PR TITLE
using imported pagination reducers in searchSlice

### PR DESCRIPTION
**Pull request by bedicooper**
making searchSlice code similar to the others by using imported reducers

### CODE REVIEW

**Review by patrycja-gomza — APPROVED** [review]
🚀 Excellent work, @bedicooper! 🚀

I've thoroughly reviewed the changes, and I'm impressed with the enhancements you've made to the searchSlice. You've not only improved the consistency but also made the codebase more maintainable.

Thank you for your valuable contribution! 👏

Approved! 🎉

**Comment by bedicooper** [comment]
I have an idea

**Comment by bedicooper** [comment]
I have an idea how to refactor pagination component to instead of dispatching actions onClick would push a page number to URL, than each page with list (movie people and searches) would .get pagination param from URL and pass it to respective saga to fetch adequate data from API.
In this case we would not need pagination reducers at all.
Similarly we would handle the search query, updating the URL onChange. This way we won't be using states properties values to change any URL and I think it will solve our issues.
I'm off for the weekend, and will be able to implement the solution on Monday.
I will hold off merging this PR as it might prove to be unnecessary in the end.

**Comment by patrycja-gomza** [comment]
> I have an idea how to refactor pagination component to instead of dispatching actions onClick would push a page number to URL, than each page with list (movie people and searches) would .get pagination param from URL and pass it to respective saga to fetch adequate data from API. In this case we would not need pagination reducers at all. Similarly we would handle the search query, updating the URL onChange. This way we won't be using states properties values to change any URL and I think it will solve our issues. I'm off for the weekend, and will be able to implement the solution on Monday. I will hold off merging this PR as it might prove to be unnecessary in the end.

I must say that I am very impressed by your engagement and very curious about your idea, which promises to be a brilliant solution 🙌🚀

Your persistence in providing the best solution is commendable. 🙏

Thank you for your hard work and have a great weekend! 🌞🌈

**Pull request closed without merging**
