### PR TITLE
conditions for missing properties added to functions

### PR DESCRIPTION
**Pull request by bedicooper**
I've added some conditions to our processing functions to handle cases of missing properties in API response.
This solution seams to work for issues we've encountered so far, but im not sure if it would handle all possible API response corruptions. We would need to perform in-depth beta testing to catch more possible problems.

### CODE REVIEW

**Review by patrycja-gomza — APPROVED** [review]
🚀 Approved! Great work on adding conditions to handle cases of missing properties in the API response. It's a good step towards improving the robustness of our application.

Keep up the excellent work! 👏👍

**Comment by bedicooper** [comment]
I've added some more safeguards:
1. checking whether the _release_date_ or _birthday_ is the expected string (namely is it a string and is it convertable to a Date object)
2. not only cheking if genres_ids exists but if it is an array, not a single number. For instance `genres_ids: 14` instead of `genres_ids: [14]`
3. if vote_average value is not a Number but a string representation of a number, we convert it to a number for processing

**Review by patrycja-gomza — APPROVED** [review]
🚀 Great job on implementing additional safeguards to enhance the reliability of our application. Your efforts in fortifying the code against potential issues are commendable. The changes look solid, and I'm confident they will contribute positively to the overall stability of our application.

Well done! Approved! 👏👍

**Review by widmo200 — APPROVED** [review]
Good job

**Pull request merged**
