### PR TITLE
Tile.js file deleted; bugs fixed in Tile/styled.js 

### PR DESCRIPTION
**Pull request by bedicooper**

### CODE REVIEW

**Review by patrycja-gomza — CHANGES_REQUESTED** [review]
Hi @bedicooper 👋

🌟 Thanks for your contribution to the project! However, I noticed that after your recent PR, there are some issues related to the removal of the Tile.js file. This file was being used in other parts of the application, causing errors during compilation.

To fix this, we need to update references to the Tile.js file in files that used it. Based on the console errors, it seems that two files are affected:
./src/features/movies/MovieDetails/index.js
./src/features/people/PeopleList/index.js

Please check these files and update references to Tile.js. Instead of using the path '../../../common/Tile/Tile', use the current path after the removal of Tile.js.

After making these changes, the errors should disappear, and the application should compile correctly. Thanks a lot in advance for making these adjustments! 🙌

**Comment by bedicooper** [comment]
Earlier today we merged Pull Requests #35-37 that removed imports from deleted Tile/Tile.js.
Currently all pages should import components from new files Tile/index.js and Tile/styled.js so after merging there shouldn't be a problem, but I will check again to be sure.

**Comment by patrycja-gomza** [comment]
Hi @bedicooper 👋

🌟 Thanks for the prompt response and for merging Pull Requests #35-37! I appreciate your efforts in addressing the removal of Tile/Tile.js imports.

If the latest changes include references to the new files Tile/index.js and Tile/styled.js in the affected files and the application now compiles without errors, that's fantastic! 

Great job on the quick resolution! 🙌 Approving this pull request. 👍

**Review by patrycja-gomza — APPROVED** [review]
Hi @bedicooper 👋

🌟 Thanks for the prompt response and for merging Pull Requests #35-37! I appreciate your efforts in addressing the removal of Tile/Tile.js imports.

If the latest changes include references to the new files Tile/index.js and Tile/styled.js in the affected files and the application now compiles without errors, that's fantastic! 

Great job on the quick resolution! 🙌 Approving this pull request. 👍

**Pull request merged**
