### PR TITLE
Common/use url params in search

### PR DESCRIPTION
**Pull request by bedicooper**
Guys, I've added a replaceQueryParameter hook to utils/useURLParams, and then I implemented it in _common\Navigation\Search\index.js_

**an issue:** If you searched for results and from them go to one of the details, the search params are left in URL, exapmple:
1. type `wonka` URL changes to `/movies?page=1&search=wonka`
2. click on Wonka movie for details, URL changes to `/movies/787699?page=1&search=wonka`

I think its because MovieDetail (and PeopleDetail alike) page does not update the URL in any way ?

**a second issue:** param order. I think its alphabetical so page comes before search. It would be more user friendly to have it the other way around, but I don't know how to achive that yet.

**a bug**: if You manually backspace the input, the search page disapears but `?page=1&search=w` is left in the URL 😩 

maybe You can think of something to addess issues above.

PS: so far in only pushes the path to URL, changeing manually does not affect the app yet.

### CODE REVIEW

**Comment by bedicooper** [comment]
edit:

I've implemented the feature that the search query updates on manual change in the URL params. 

And found some other strage behaviours:
1. when typing the search param manually noResults page flashes before rendering search results 🙃 
2. after manualy typing the search param in URL does not always update nuber of pages in pagination 🤔 
3. copy/pasting of the URL does not seem to work with search results - maybe its a localhost problem but im not sure 😫 

please review my solutions, maybe You find fixes for problems mentioned above.
I'm blanking right now and need some fresh air to clear my head.

**Comment by widmo200** [comment]
I'm also looking for a solution

**Comment by bedicooper** [comment]
Ok, clearly there was a problem with

**Comment by bedicooper** [comment]
I've worked and reworked URL handling in search reaching similar results or rather bugs. The behavior of the app now looks more stable, but 3 problems remain:
1. copying the URL does not take us to the search page
2. using text from input leaves the last letter in `search=` param
3. pagination does not reset when changing the input

I don't have any more ideas. We could merge this solution and try to change it tomorrow, at least something happens to URL on input 😞

**Review by patrycja-gomza — APPROVED** [review]
Hi @bedicooper 👋
Unfortunately, I haven't found another better solution, so I'm for joining your solution in our branch. Let's do it 🚀

**Pull request merged**
